<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8741f469-cf84-4ab5-944b-b514f0622b0f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Holmsgaard.ApiService\Holmsgaard.ApiService.csproj" />
    <ProjectReference Include="..\Holmsgaard.Web\Holmsgaard.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.0" />
  </ItemGroup>

</Project>
